# Generated by Django 4.1.13 on 2023-12-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0002_etc_people_work_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainText', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.ImageField(default='images/none/no-img.jpg', upload_to='images/'),
        ),
    ]
