# Generated by Django 4.1.13 on 2023-12-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0005_mainimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimage',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
