# Generated by Django 4.1.13 on 2023-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0008_alter_mainnewsbox_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnewsbox',
            name='text',
            field=models.TextField(),
        ),
    ]
