# Generated by Django 4.1.13 on 2023-12-07 07:25

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0009_alter_mainnewsbox_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnewsbox',
            name='text',
            field=django_quill.fields.QuillField(),
        ),
    ]
