# Generated by Django 4.1.13 on 2023-12-08 03:17

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0010_alter_mainnewsbox_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='text',
            field=django_quill.fields.QuillField(default=''),
        ),
    ]
