# Generated by Django 4.1.13 on 2023-12-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0011_people_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/none/no-img.jpg', upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='etc',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
