# Generated by Django 4.1.13 on 2023-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0012_faculty_delete_etc_delete_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='lab',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
