# Generated by Django 4.1.13 on 2023-12-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0013_alter_faculty_lab_alter_faculty_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
