# Generated by Django 4.1.13 on 2023-12-08 07:45

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0014_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/none/no-img.jpg', upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('text', django_quill.fields.QuillField(default='')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
