# Generated by Django 4.1.13 on 2023-12-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0015_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
