# Generated by Django 4.1.13 on 2023-12-09 00:33

from django.db import migrations, models
import django.utils.timezone
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0016_lab_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/none/no-img.jpg', upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('text', django_quill.fields.QuillField(default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('detailname', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('brandyear', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
