# Generated by Django 4.1.13 on 2023-12-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0017_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='detailname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
