# Generated by Django 4.1.13 on 2023-12-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uddApp', '0019_exhibition_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
